//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliseev.NoCyrillicInCodeAnalyzer {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eliseev.NoCyrillicInCodeAnalyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0001AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0001AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0001AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0001AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0001AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0001AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Namespaces must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0002AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0002AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Namespace &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0002AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0002AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Namespace must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0002AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0002AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0003AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0003AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0003AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0003AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Method name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0003AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0003AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0004AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0004AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0004AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0004AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0004AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0004AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Properties names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0005AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0005AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0005AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0005AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Property name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0005AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0005AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0006AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0006AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0006AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0006AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0006AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0006AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0007AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0007AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0007AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0007AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parameter name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0007AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0007AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type parameter names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0008AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0008AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type parameter name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0008AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0008AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type parameter name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0008AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0008AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enum names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0009AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0009AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enum name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0009AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0009AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enum name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0009AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0009AnalyzerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event names must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0010AnalyzerDescription {
            get {
                return ResourceManager.GetString("NC0010AnalyzerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event name &apos;{0}&apos; contains Cyrillic letters.
        /// </summary>
        internal static string NC0010AnalyzerMessageFormat {
            get {
                return ResourceManager.GetString("NC0010AnalyzerMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Event name must not contain Cyrillic letters.
        /// </summary>
        internal static string NC0010AnalyzerTitle {
            get {
                return ResourceManager.GetString("NC0010AnalyzerTitle", resourceCulture);
            }
        }
    }
}
