//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliseev.NoCyrillicInCodeAnalyzer {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eliseev.NoCyrillicInCodeAnalyzer.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0001CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0001CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0002CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0002CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0003CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0003CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0004CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0004CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0005CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0005CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0006CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0006CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0007CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0007CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0008CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0008CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0009CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0009CodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Replace Cyrillic letters with Latin.
        /// </summary>
        internal static string NC0010CodeFixTitle {
            get {
                return ResourceManager.GetString("NC0010CodeFixTitle", resourceCulture);
            }
        }
    }
}
